apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: github-dotnet-azure-060625xx 
  janus-idp.io/tekton: github-dotnet-azure-060625xx
  backstage.io/kubernetes-id: github-dotnet-azure-060625xx
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: github-dotnet-azure-060625xx
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml