apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: github-dotnet-azure-060625xx-gitops
  description: This is GitOps manifest for github-dotnet-azure-060625xx   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=github-dotnet-azure-060625xx
    backstage.io/kubernetes-id: github-dotnet-azure-060625xx 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: rhtap-qe-jsmid/github-dotnet-azure-060625xx-gitops
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: rhtap-qe-jsmid.github-dotnet-azure-060625xx-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:github-dotnet-azure-060625xx
