apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: github-dotnet-azure-060625xx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-dotnet-azure-060625xx 
  name: github-dotnet-azure-060625xx
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: github-dotnet-azure-060625xx
    weight: 100 
