apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: github-dotnet-azure-060625xx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-dotnet-azure-060625xx 
  name: github-dotnet-azure-060625xx
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: github-dotnet-azure-060625xx 
